<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TokensControllerTest extends TestCase {

    use RefreshDatabase, withFaker;

    /**
     * @var User|null
     */
    private $user = null;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed('TestSeeder');

        // Create a new user to test with //
        $this->user = User::all()->random();
    }

    /**
     * Test user can generate a token
     * @return void
     */
    public function testCreateAToken(): void {
        $response = $this->actingAs($this->user)
                         ->postJson("/api/v1/users/{$this->user->id}/tokens",
                                    ["token_name" => 'test-token']
                         );

        $response->assertStatus(201);
    }

    /**
     * Test a user can get their tokens
     */
    public function testGetTokens(): void {
        $response = $this->actingAs($this->user)
                         ->getJson("/api/v1/users/{$this->user->id}/tokens");

        $response->assertStatus(200);
    }

    public function testDeleteToken(): void {

        $token = $this->user->tokens->random();

        $response = $this->actingAs($this->user)
                         ->delete("/api/v1/users/{$this->user->id}/tokens/{$token->id}");

        $response->assertStatus(204);
    }
}
