<template>
    <div id="api">
        <div class="row justify-content-center">
            <div class="col-sm-10 mb-2">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="card mb-2">
                            <h1 class="card-header text-center">Interacting</h1>
                            <div class="card-body">
                                <dl>
                                    <dt>
                                        Preparing to interact with the API
                                    </dt>
                                    <dd>
                                        In order to interact with the API, you must have a pre-qualified access token.
                                    </dd>
                                    <dd>
                                        Register an account, verify your email address, then click on the context menu under your name
                                        in the right hand of the navigation bar. Select the "Access Tokens" option.
                                    </dd>
                                    <dd>
                                        In the Access Tokens page, you will see your previous access keys if available, and the ability to
                                        create a new token. Use the form to generate a token, which will only be visible until the page
                                        refreshes. At that time, you will need to generate another token.
                                        <strong>Copy this token, you will need to use it for API requests.</strong>
                                    </dd>
                                    <dt>
                                        Using your 'key' and 'token'
                                    </dt>
                                    <dd>
                                        Every request needs to include a token. This token is generated by following the instructions above.
                                        Attach this token as a <code>`Authorization Bearer`</code> header.
                                    </dd>
                                    <dt>
                                        Requests: All requests should have the following headers
                                    </dt>
                                    <dd>
                                        <code>Accept: application/json</code>
                                    </dd>
                                    <dd>
                                        <code>Authorization: bearer {token}</code>
                                    </dd>
                                    <dt>
                                        Variables: Variables are surrounded by brackets `{variable_name}`
                                    </dt>
                                    <dd>
                                        <code>host</code>: https://springnotes.loc/api/v1
                                    </dd>
                                    <dd>
                                        <code>note</code>: Note ID
                                    </dd>
                                    <dd>
                                        <code>user</code>: User ID
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <h1 class="text-center">Usage</h1>
            </div>
        </div>

        <div class="row my-3">
            <div class="col">
                <h2 class="text-center">Notes</h2>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col">
                <ExampleComponent :requests="Examples.requests.notes"/>
            </div>
        </div>

        <div class="row my-3">
            <div class="col">
                <h2 class="text-center">User</h2>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col">
                <ExampleComponent :requests="Examples.requests.user"/>
            </div>
        </div>

    </div>

</template>

<script>
import Examples from './examples.json';

const ExampleComponent = () => import('./ExampleComponent');

export default {
    data() {
        return {
            Examples: Examples
        }
    },
    mounted() {
        // Add prettyprint cdn to page //
        let pretty = document.createElement('script');
        pretty.setAttribute('src', 'https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?skin=desert');
        document.head.appendChild(pretty);
    },
    components: {
        ExampleComponent
    }
}
</script>
