<template>
    <div id="api">
        <div class="row">
            <div class="offset-11">
                <div class="position-fixed pt-5">
                    <a class="d-block" href="#interacting">Interacting</a>
                    <a class="d-block" href="#notes">Notes</a>
                    <a class="d-block" href="#auth">Auth</a>
                    <a class="d-block" href="#user">User</a>
                    <a class="d-block" href="#tokens">Tokens</a>
                    <a class="d-block" href="#comments">Comments</a>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-sm-10 mb-2">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="card mb-2">
                            <h1 id="interacting" class="card-header text-center">Interacting</h1>
                            <div class="card-body">
                                <dl>
                                    <dt>
                                        Preparing to interact with the API
                                    </dt>
                                    <dd>
                                        In order to interact with the API, you must have a pre-qualified access token.
                                    </dd>
                                    <dd>
                                        Register an account, verify your email address, then click on the context menu under your name
                                        in the right hand of the navigation bar. Select the "Access Tokens" option.
                                    </dd>
                                    <dd>
                                        In the Access Tokens page, you will see your previous access keys if available, and the ability to
                                        create a new token. Use the form to generate a token, which will only be visible until the page
                                        refreshes. At that time, you will need to generate another token. <br>
                                        <i><strong>Note:</strong> Copy this token, you will need to use it for API requests.</i>
                                    </dd>
                                    <dt>
                                        Using your 'key' and 'token'
                                    </dt>
                                    <dd>
                                        Every request needs to include a token. This token is generated by following the instructions above.
                                        Attach this token as a <code>`Authorization Bearer`</code> header.
                                    </dd>
                                    <dt>
                                        Requests: All requests should have the following headers
                                    </dt>
                                    <dd>
                                        <code>Accept: application/json</code>
                                    </dd>
                                    <dd>
                                        <code>Authorization: bearer {token}</code>
                                    </dd>
                                    <dt>
                                        Variables: Variables are surrounded by brackets `{variable_name}`
                                    </dt>
                                    <dd>
                                        <code>base_host</code>: https://springnotes.loc <br>
                                        <i>
                                            <strong>Note:</strong>To use these endpoints, you will need to pass a
                                            <code>X-XSRF-TOKEN</code> as a header
                                        </i>
                                    </dd>
                                    <dd>
                                        <code>host</code>: https://springnotes.loc/api/v1
                                    </dd>
                                    <dd>
                                        <code>note</code>: Note ID
                                    </dd>
                                    <dd>
                                        <code>user</code>: User ID
                                    </dd>
                                    <dd>
                                        <code>comment</code>: Comment ID
                                    </dd>
                                    <dd>
                                        <code>token</code>: Token ID
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>Error Response</dt>
                                    <dd>Form errors will return the following error response bodies</dd>
                                </dl>
                                <pre class="prettyprint lang-json">{{ JSON.stringify(error_body, null, 4) }}</pre>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col">
                <h1 class="text-center">Usage</h1>
            </div>
        </div>

        <ExampleComponent :header="e_key" :key="e_key" :requests="e_result" v-for="(e_result, e_key) in examples"/>
    </div>
</template>

<script>
import auth from './Examples/auth.json';
import comments from './Examples/comments.json';
import notes from './Examples/notes.json';
import search from './Examples/search.json';
import tokens from './Examples/tokens.json';
import user from './Examples/user.json';

const ExampleComponent = () => import('./ExampleComponent');

export default {
    data() {
        return {
            examples: {
                notes,
                auth,
                user,
                tokens,
                comments,
                search
            },
            error_body: {
                "message": "The given data was invalid.",
                "errors": {
                    "example_field_1": [
                        "error",
                        "messages"
                    ],
                    "example_field_2": [
                        "pertaining",
                        "to field"
                    ]
                }
            }
        }
    },
    mounted() {
        // Add prettyprint cdn to page //
        let pretty = document.createElement('script');
        pretty.setAttribute('src', 'https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?skin=desert');
        document.head.appendChild(pretty);
    },
    components: {
        ExampleComponent
    }
}
</script>
